workflows:
  ios-workflow:
    name: iOS Build (Free Account)
    environment:
      groups:
        - supabase_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build IPA without code signing
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/Runner.xcworkspace" \
            --scheme "Runner" \
            --disable-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - crazynoob1566@gmail.com