workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - supabase_credentials
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Build iOS app
        script: |
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          cd $CM_BUILD_DIR
          mkdir -p build/ios/ipa/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/Runner.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com