workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - supabase_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Generate Flutter files
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
          flutter build ios --config-only --no-codesign
      - name: Manual IPA creation
        script: |
          cd $CM_BUILD_DIR/ios
          
          # Собираем приложение без архивирования
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
          # Создаем структуру IPA вручную
          mkdir -p Payload
          cp -r build/Release-iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload
          
          # Копируем IPA в нужное место
          mkdir -p $CM_BUILD_DIR/build/ios/ipa
          cp Runner.ipa $CM_BUILD_DIR/build/ios/ipa/
      - name: Verify artifacts
        script: |
          echo "Проверка артефактов:"
          find $CM_BUILD_DIR -name "*.ipa" -type f
          ls -la $CM_BUILD_DIR/build/ios/ipa/ || echo "Папка ipa не существует"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com