workflows:
  ios-workflow:
    name: iOS Build (Free Account)
    environment:
      groups:
        - supabase_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Build IPA without code signing
        script: |
          # Создаем архив без подписи
          xcodebuild archive \
            -workspace "$CM_BUILD_DIR/ios/Runner.xcworkspace" \
            -scheme Runner \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/build/Runner.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          # Экспортируем IPA без подписи
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/Runner.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ios/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - crazynoob1566@gmail.com