workflows:
  ios-workflow:
    name: iOS Build (Free Account)
    environment:
      groups:
        - supabase_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          cd $CM_BUILD_DIR
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Build IPA without code signing
        script: |
          cd $CM_BUILD_DIR
          flutter build ipa \
            --release \
            --no-codesign \
            --export-options-plist="$CM_BUILD_DIR/ios/exportOptions.plist"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com