workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - supabase_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up Flutter
        script: |
          flutter packages pub get
      - name: Generate Flutter files
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
          # Генерируем необходимые файлы для iOS
          flutter build ios --config-only --no-codesign
      - name: Build with xcodebuild
        script: |
          cd $CM_BUILD_DIR/ios
          
          # Создаем архив без подписи
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          
          # Создаем папку для IPA
          mkdir -p build/ipa
          
          # Экспортируем IPA
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
          
          # Копируем IPA в ожидаемое место
          mkdir -p $CM_BUILD_DIR/build/ios/ipa
          cp build/ipa/*.ipa $CM_BUILD_DIR/build/ios/ipa/
      - name: Verify artifacts
        script: |
          echo "Проверка артефактов:"
          find $CM_BUILD_DIR -name "*.ipa" -type f
          ls -la $CM_BUILD_DIR/build/ios/ipa/
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com