workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - supabase_credentials
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          echo "Настройка Flutter..."
          flutter packages pub get
      - name: Generate iOS files
        script: |
          echo "Генерация iOS файлов..."
          cd $CM_BUILD_DIR
          flutter create --platforms=ios --org com.example --project-name my_chat_app .
      - name: Build iOS app
        script: |
          echo "Сборка iOS приложения..."
          cd $CM_BUILD_DIR
          flutter build ios --release --no-codesign --no-pub
      - name: Create IPA manually
        script: |
          echo "Создание IPA файла..."
          cd $CM_BUILD_DIR
          
          # Создаем папку для IPA
          mkdir -p build/ios/ipa/Payload
          
          # Копируем приложение
          cp -R build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          
          # Создаем IPA
          cd build/ios/ipa
          zip -r Runner.ipa Payload
          
          echo "Размер IPA:"
          du -sh Runner.ipa
          
          # Проверяем содержимое IPA
          echo "Содержимое IPA:"
          unzip -l Runner.ipa | head -10
      - name: Verify artifacts
        script: |
          echo "Проверка артефактов:"
          find $CM_BUILD_DIR -name "*.ipa" -type f -exec du -sh {} \;
          ls -la $CM_BUILD_DIR/build/ios/ipa/
    artifacts:
      - build/ios/ipa/Runner.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com