name: my_chat_app
description: "A personal chat application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  mime: ^1.0.4
  path_provider: ^2.1.1
  image: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true